
---
- hosts: all
  sudo: True

  tasks:
  - name: Install pip.
    yum: name={{ item }}
         state=present
    with_items:
    - python-pip
    - python-setuptools
    - python-dev
    - numpy
    - scipy
