---
- hosts: all
  sudo: true
  tasks:
    - name: Install R packages from CRAN
      shell: echo "options(repos=structure(c(CRAN='{{ "http://cran.us.r-project.org" }}/')));if(require({{ item }})){}else{install.packages('{{ item }}');library({{ item }})}" | /usr/bin/R --no-save
      with_items:
        - quadprog
        - popbio
        - Matrix
        - expm
        - ggplot2
        - data.table
        - lme4
        - reshape
        - MatrixEQTL
        # - popdemo
      notify: R changed
      with_items:
        - DESeq2
        - edgeR
  handlers:
    - name: R changed
      set_fact: r_changed=True
